import type { Exercise } from '@/types/exercises';

export const exercises: Exercise[] = [
  // ── BRUST ──────────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Bench Press',
    nameDE: 'Bankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeight: 60,
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    nameDE: 'Schrägbankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 50,
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    nameDE: 'Kurzhantel Bankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 24,
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    nameDE: 'Kabelzug Flyes',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 15,
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    nameDE: 'Kurzhantel Flyes',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
  },
  {
    id: 'push-up',
    name: 'Push Up',
    nameDE: 'Liegestütz',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 0,
  },
  {
    id: 'dips',
    name: 'Dips',
    nameDE: 'Dips',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
  },

  // ── RÜCKEN ─────────────────────────────────────────────────────────────────
  {
    id: 'deadlift',
    name: 'Deadlift',
    nameDE: 'Kreuzheben',
    primaryMuscle: 'back',
    secondaryMuscles: ['glutes', 'legs', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 5,
    defaultWeight: 100,
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    nameDE: 'Langhantelrudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeight: 70,
  },
  {
    id: 'pull-up',
    name: 'Pull Up',
    nameDE: 'Klimmzug',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeight: 0,
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    nameDE: 'Latzug',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 10,
    defaultWeight: 60,
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    nameDE: 'Kabelzug Rudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 50,
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    nameDE: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 20,
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    nameDE: 'Kurzhantelrudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 24,
  },

  // ── SCHULTERN ──────────────────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    nameDE: 'Schulterdrücken',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeight: 50,
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    nameDE: 'Kurzhantel Schulterdrücken',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 18,
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    nameDE: 'Seitheben',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 4,
    defaultReps: 15,
    defaultWeight: 8,
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    nameDE: 'Vorwärtsheben',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: ['dumbbell', 'barbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 8,
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    nameDE: 'Reverse Flyes',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['dumbbell', 'cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
  },

  // ── BIZEPS ─────────────────────────────────────────────────────────────────
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    nameDE: 'Langhantel Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    category: 'isolation',
    defaultSets: 4,
    defaultReps: 10,
    defaultWeight: 30,
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    nameDE: 'Kurzhantel Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 14,
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    nameDE: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 14,
  },
  {
    id: 'incline-curl',
    name: 'Incline Dumbbell Curl',
    nameDE: 'Schrägbank Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    nameDE: 'Kabel Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 20,
  },

  // ── TRIZEPS ────────────────────────────────────────────────────────────────
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    nameDE: 'Trizeps Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 4,
    defaultReps: 12,
    defaultWeight: 30,
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    nameDE: 'Skull Crusher',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['barbell', 'dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 30,
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    nameDE: 'Trizeps Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['dumbbell', 'cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 20,
  },
  {
    id: 'close-grip-bench',
    name: 'Close Grip Bench Press',
    nameDE: 'Enges Bankdrücken',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 50,
  },

  // ── BEINE ──────────────────────────────────────────────────────────────────
  {
    id: 'squat',
    name: 'Squat',
    nameDE: 'Kniebeuge',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeight: 80,
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    nameDE: 'Beinpresse',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 10,
    defaultWeight: 120,
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    nameDE: 'Beinstrecker',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 40,
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    nameDE: 'Beinbeuger',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 35,
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    nameDE: 'Rumänisches Kreuzheben',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes', 'back'],
    equipment: ['barbell', 'dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 70,
  },
  {
    id: 'lunges',
    name: 'Lunges',
    nameDE: 'Ausfallschritte',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['barbell', 'dumbbell', 'bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    nameDE: 'Bulgarische Kniebeuge',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['barbell', 'dumbbell', 'bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 0,
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    nameDE: 'Hack Squat',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 10,
    defaultWeight: 80,
  },

  // ── GESÄSS ──────────────────────────────────────────────────────────────────
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    nameDE: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['legs'],
    equipment: ['barbell'],
    category: 'isolation',
    defaultSets: 4,
    defaultReps: 12,
    defaultWeight: 60,
  },
  {
    id: 'cable-kickback',
    name: 'Cable Kickback',
    nameDE: 'Kabel Kickback',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 15,
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    nameDE: 'Plank',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 1,
    defaultWeight: 0,
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    nameDE: 'Kabel Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 20,
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    nameDE: 'Hängendes Beineheben',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 0,
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    nameDE: 'Ab-Rad Rollout',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 0,
  },

  // ── WADEN ──────────────────────────────────────────────────────────────────
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    nameDE: 'Wadenheben',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['machine', 'barbell', 'dumbbell', 'bodyweight'],
    category: 'isolation',
    defaultSets: 4,
    defaultReps: 20,
    defaultWeight: 40,
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    nameDE: 'Sitzend Wadenheben',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 4,
    defaultReps: 20,
    defaultWeight: 30,
  },
];

// Helper: Übung nach ID finden
export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((e) => e.id === id);
}

// Helper: Übungen nach Muskelgruppe filtern
export function getExercisesByMuscle(muscle: string): Exercise[] {
  return exercises.filter(
    (e) => e.primaryMuscle === muscle || e.secondaryMuscles.includes(muscle as never)
  );
}

// Helper: Übungen nach Equipment filtern
export function getExercisesByEquipment(equipment: string): Exercise[] {
  return exercises.filter((e) => e.equipment.includes(equipment as never));
}
