import type { Exercise } from '@/types/exercises';

export const exercises: Exercise[] = [

  // ── CHEST ──────────────────────────────────────────────────────────────────

  {
    id: 'bench-press',
    name: 'Barbell Bench Press',
    nameDE: 'Langhantel Bankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 8,
    defaultWeight: 60,
    repRange: { min: 6, max: 10 },
    restSeconds: 180,
    scienceNote: 'Keep elbows ~75° from torso to minimize shoulder impingement. Higher EMG pec activation than any DB variation. Drive feet into the floor and retract scapulae for a stable base.',
  },
  {
    id: 'incline-dumbbell-press',
    name: 'Incline Dumbbell Press',
    nameDE: 'Kurzhantel Schrägbankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 22,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: '30–45° incline maximizes upper pec (clavicular head) activation. Free ROM allows natural shoulder path — easier on AC joint than barbell. Rotate wrists slightly inward at top for peak contraction.',
  },
  {
    id: 'incline-barbell-press',
    name: 'Incline Barbell Press',
    nameDE: 'Langhantel Schrägbankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 50,
    repRange: { min: 6, max: 10 },
    restSeconds: 150,
    scienceNote: 'Jeff Nippard rates this as his cornerstone chest exercise — 45° incline, slightly narrower grip increases ROM and triceps engagement. Touch the upper chest, not the clavicle.',
  },
  {
    id: 'seated-cable-fly',
    name: 'Seated Cable Fly',
    nameDE: 'Kabelzug Flyes (sitzend)',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
    repRange: { min: 10, max: 15 },
    restSeconds: 75,
    scienceNote: 'Seated position locks the lower body — all tension goes to the pec. Cable provides constant tension through full ROM unlike DBs. Bring elbows together at the front for maximum peak contraction.',
  },
  {
    id: 'pec-deck',
    name: 'Pec Deck / Machine Fly',
    nameDE: 'Butterfly Maschine',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 50,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Machine fly allows pure pec isolation without stabilizer fatigue — ideal as a finisher. Slow 3-second eccentric increases time under tension and mechanical stretch stimulus.',
  },
  {
    id: 'dips',
    name: 'Dips (Chest Focused)',
    nameDE: 'Dips (Brust-Fokus)',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
    repRange: { min: 8, max: 15 },
    restSeconds: 90,
    scienceNote: 'Lean forward 15–20° to shift focus to pec major. Flare elbows slightly out. Deep ROM at bottom gives significant pec stretch — add weight with belt once bodyweight becomes easy.',
  },
  {
    id: 'cable-pullover',
    name: 'Cable Pullover',
    nameDE: 'Kabelzug Überzüge',
    primaryMuscle: 'back',
    secondaryMuscles: ['chest', 'core'],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 15,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Jeff Nippard favorites: set cable higher than shoulder level. Initiate with lats, keep elbows locked. Maximizes mechanical tension on the lat in the lengthened position. Better than DB version because of constant cable tension profile.',
  },
  {
    id: 'dumbbell-pullover',
    name: 'Dumbbell Pullover',
    nameDE: 'Kurzhantel Überzüge',
    primaryMuscle: 'back',
    secondaryMuscles: ['chest', 'triceps'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 24,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Traditional mass builder. Lie across the bench (Arnold style) if possible. Deep stretch at bottom. Primarily targets the long head of triceps and serratus, but also works the lower pec and upper lats.',
  },
  {
    id: 'bayesian-cable-fly',
    name: 'Bayesian Cable Fly',
    nameDE: 'Bayesian Flyes (Kabel)',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 10,
    repRange: { min: 12, max: 20 },
    restSeconds: 75,
    scienceNote: 'Chest variation of the Bayesian curl concept. Set cables slightly behind torso to load the chest in the most lengthened position. Science shows 30% more hypertrophy for the pec when trained in this deep stretch.',
  },
  {
    id: 'lu-raise',
    name: 'Lu Raise',
    nameDE: 'Lu Raises',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 5,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Full-range lateral raise (all the way overhead). Builds incredible shoulder mobility and lateral delt endurance. Named after Chinese weightlifter Lu Xiaojun. Use very light weight.',
  },

  // ── BACK ───────────────────────────────────────────────────────────────────

  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    nameDE: 'Latzug',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 60,
    repRange: { min: 8, max: 12 },
    restSeconds: 90,
    scienceNote: 'Pull bar to upper sternum — never behind neck (cervical stress). Lean slightly back, chest up. Initiate with scapular depression before elbow flexion. Can be done uni- or bilateral.',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    nameDE: 'Kabelzug Rudern (sitzend)',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 55,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Fully retract scapulae at peak contraction — accounts for 30% of the movement. Keep torso upright, avoid swinging. Pronated grip targets upper back; neutral grip emphasizes lats more.',
  },
  {
    id: 'cable-shrugs',
    name: 'Cable Shrugs',
    nameDE: 'Kabelzug Schulterziehen',
    primaryMuscle: 'back',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 50,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Cable maintains constant tension unlike barbells. Shrug straight up — no rolling. Hold 1–2 seconds at top for full trap contraction. Targets upper trapezius for thickness and posture.',
  },
  {
    id: 'pull-up',
    name: 'Pull Up',
    nameDE: 'Klimmzug',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 0,
    repRange: { min: 6, max: 12 },
    restSeconds: 120,
    scienceNote: 'Jeff Nippard rates weighted pull-ups as S-tier. Depress scapulae first before bending elbows. Pause at bottom for full lat stretch. Add weight with belt when reps exceed 12.',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    nameDE: 'Kurzhantelrudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 26,
    repRange: { min: 8, max: 12 },
    restSeconds: 90,
    scienceNote: 'Full scapular retraction at top — higher loads possible than cable rows. Brace the support hand actively. Neutral grip with elbow close to body maximizes lat activation.',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    nameDE: 'Langhantelrudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 70,
    repRange: { min: 6, max: 10 },
    restSeconds: 120,
    scienceNote: 'Torso 45°, pull bar to navel. Fully retract scapulae at the top. Underhand (supinated) grip produces highest lat EMG. Pendlay-style (deload each rep) increases ROM and eliminates momentum.',
  },
  {
    id: 'chest-supported-row',
    name: 'Chest-Supported Row',
    nameDE: 'Brustgestütztes Rudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 22,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Chest support removes lower back from the equation — pure mid-back and rhomboid work. Allows scapular protraction at bottom for full ROM. Great substitute when lower back is fatigued.',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    nameDE: 'Gesichtszug (Face Pull)',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 18,
    repRange: { min: 15, max: 25 },
    restSeconds: 60,
    scienceNote: 'Pull to ear height, elbows high. Essential for posterior delt and rotator cuff health. Significantly reduces shoulder injury risk from pressing. Include every session as shoulder prehab.',
  },

  // ── SHOULDERS ──────────────────────────────────────────────────────────────

  {
    id: 'arnold-press',
    name: 'Arnold Press',
    nameDE: 'Arnold Press (sitzend)',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 16,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Rotation through the pressing motion activates all three delt heads sequentially — anterior, medial, and posterior — making it superior to standard DB press for complete shoulder development.',
  },
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    nameDE: 'Schulterdrücken (Langhantel)',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 50,
    repRange: { min: 6, max: 10 },
    restSeconds: 180,
    scienceNote: 'Brace core, glutes, and legs tightly — bar travels in a slight arc just in front of the face. Highest overall shoulder loading of any pressing exercise. Great strength indicator.',
  },
  {
    id: 'cable-lateral-raise',
    name: 'Lateral Raise',
    nameDE: 'Kabelzug Seitheben',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Jeff Nippard rates cable lateral raises as S+ tier — sweep the weight out (not up) to maximize medial delt tension. Cable provides constant tension unlike dumbbells. Avoid shrugging.',
  },
  {
    id: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    nameDE: 'Kurzhantel Seitheben',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Tilt thumbs slightly down (like pouring water) for better medial delt isolation. Controlled 3-second eccentric maximizes time under tension. Nearly irreplaceable for shoulder width.',
  },
  {
    id: 'reverse-pec-deck',
    name: 'Reverse Pec Deck',
    nameDE: 'Reverse Butterfly (Maschine)',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 40,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Posterior delt is often underdeveloped and undertrained. Rear delt work improves shoulder balance, posture, and reduces pressing injuries. Machine isolates better than bent-over DB fly.',
  },
  {
    id: 'rear-delt-cable-fly',
    name: 'Rear Delt Cable Fly',
    nameDE: 'Hinteres Seitheben am Kabel',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Set cables at head height, cross-body pull. Constant cable tension hits the posterior delt through full ROM. Slight elbow bend — focus on pinching the shoulder blades at peak.',
  },
  {
    id: 'machine-shoulder-press',
    name: 'Machine Shoulder Press',
    nameDE: 'Maschinen Schulterdrücken',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: ['machine'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 40,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Guided path allows full focus on anterior and medial delt without stability demands. Ideal when fatigued or as a high-rep finisher. Jeff Nippard recommends machine press for consistent mechanical stress.',
  },

  // ── BICEPS ─────────────────────────────────────────────────────────────────

  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    nameDE: 'Kurzhantel Bizepscurl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 14,
    repRange: { min: 10, max: 15 },
    restSeconds: 75,
    scienceNote: 'Supinate at the top (rotate palm outward) for maximal biceps peak contraction. Keep elbows pinned at sides. Alternating arms allows unilateral focus and corrects imbalances.',
  },
  {
    id: 'reverse-cable-curl',
    name: 'Reverse Cable Curl',
    nameDE: 'Reverse Curl am Kabel',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 15,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Pronated grip shifts focus to brachialis and brachioradialis — muscles that push the biceps peak up from below. Cable ensures constant tension throughout the curl. Great for forearm development.',
  },
  {
    id: 'preacher-curl',
    name: 'Preacher Curl',
    nameDE: 'Preacher Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 30,
    repRange: { min: 10, max: 15 },
    restSeconds: 75,
    scienceNote: 'Arm resting on pad eliminates cheating — isolated short-head stretch maximizes brachialis activation. Studies show lengthened-position training produces superior hypertrophy. Use EZ bar or machine.',
  },
  {
    id: 'bayesian-cable-curl',
    name: 'Bayesian Cable Curl',
    nameDE: 'Bayesian Curl (Kabel)',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Jeff Nippard\'s favourite curl — cable set low behind the body keeps the long head stretched throughout the rep. EMG and recent hypertrophy research confirms the stretch-loaded position drives more growth.',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    nameDE: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 14,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Neutral grip hits brachialis and brachioradialis harder than standard curls. Brachialis lies beneath the biceps — growing it pushes the biceps peak up. Provides strong forearm cross-section development.',
  },

  // ── TRICEPS ────────────────────────────────────────────────────────────────

  {
    id: 'cable-overhead-tricep-ext',
    name: 'Cable Overhead Extension',
    nameDE: 'Trizeps Extension Überkopf (Kabel)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 20,
    repRange: { min: 10, max: 15 },
    restSeconds: 75,
    scienceNote: 'Overhead position puts the long head in full stretch — 2023 study shows this produces significantly more hypertrophy than pushdowns alone. Anchor cable high, elbows in line with ears, full stretch and squeeze.',
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    nameDE: 'Trizeps Pushdown (Kabel)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 30,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Elbows pinned at sides throughout. Full lock-out at bottom for peak lateral head contraction. Rope attachment allows hands to separate at bottom — greater lateral head activation vs. straight bar.',
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher (EZ Bar)',
    nameDE: 'Skull Crusher (EZ-Stange)',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['barbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 30,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Lower bar slightly behind the head — maximizes long head stretch at bottom. EZ bar reduces wrist stress. Keep elbows pointing up and together. Provides excellent long-head mass builder.',
  },
  {
    id: 'close-grip-bench',
    name: 'Close Grip Bench Press',
    nameDE: 'Enges Bankdrücken',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 50,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Grip shoulder-width (not too narrow — wrist strain). Elbows tucked close to body shift 70%+ load to triceps. Allows progressive overload with heavy weights — best compound tricep builder.',
  },
  {
    id: 'dips-triceps',
    name: 'Dips (Triceps Focused)',
    nameDE: 'Dips (Trizeps-Fokus)',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
    repRange: { min: 8, max: 15 },
    restSeconds: 90,
    scienceNote: 'Stay upright (minimal forward lean) to maximize triceps recruitment. Full extension at top for peak contraction. Add weight with belt for progressive overload.',
  },

  // ── LEGS — QUAD DOMINANT ───────────────────────────────────────────────────

  {
    id: 'smith-machine-squat',
    name: 'Smith Machine Squat',
    nameDE: 'Smith Maschine Kniebeuge',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['smith'],
    category: 'compound',
    defaultSets: 4,
    defaultReps: 10,
    defaultWeight: 70,
    repRange: { min: 8, max: 12 },
    restSeconds: 150,
    scienceNote: 'Guided track allows feet to be placed slightly forward — produces more upright torso and increased quad activation. Jeff Nippard rates this highly for quad isolation. Ideal for training alone safely.',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    nameDE: 'Beinstrecker',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 45,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Full extension and hold 1–2 seconds at top for VMO (inner quad) activation. Research shows leg extensions produce high quad hypertrophy with low spinal load — ideal complement to squats.',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    nameDE: 'Beinpresse',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 120,
    repRange: { min: 10, max: 15 },
    restSeconds: 120,
    scienceNote: 'Foot position matters: low/narrow = quad dominant; high/wide = glute/hamstring dominant. Never lock knees fully. Allows higher loads than squats with less spinal fatigue.',
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    nameDE: 'Hack Squat',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 80,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Ranked S+ for quad development by Jeff Nippard. Upright torso dramatically reduces spinal load. Low foot placement maximizes quad range of motion. Machine allows deep squat safely.',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    nameDE: 'Bulgarische Kniebeuge',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['dumbbell', 'barbell', 'bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 0,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Rear foot elevated, front foot 60–70cm forward. Studies show comparable quad activation to barbell squat with significantly lower spinal load. Unilateral work corrects strength imbalances.',
  },

  // ── LEGS — HAMSTRING/HIP DOMINANT ─────────────────────────────────────────

  {
    id: 'romanian-deadlift',
    name: 'RDL',
    nameDE: 'Rumänisches Kreuzheben (RDL)',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes', 'back'],
    equipment: ['barbell', 'dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 70,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Hip hinge (not squat) — push hips back, slight knee bend. Maximum hamstring stretch at bottom. Jeff Nippard recommends this over conventional DL for hypertrophy due to lower CNS fatigue with similar stimulus.',
  },
  {
    id: 'seated-leg-curl',
    name: 'Seated Leg Curl',
    nameDE: 'Beinbeuger (sitzend)',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 40,
    repRange: { min: 10, max: 15 },
    restSeconds: 75,
    scienceNote: 'Seated position keeps hip flexed — puts hamstrings in a stretched, lengthened position for the entire set. New research 2022–2024 consistently shows seated ham curl produces superior hypertrophy over lying variation.',
  },
  {
    id: 'lying-leg-curl',
    name: 'Lying Leg Curl',
    nameDE: 'Beinbeuger (liegend)',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 40,
    repRange: { min: 10, max: 15 },
    restSeconds: 75,
    scienceNote: 'Classic hamstring curl targeting the biceps femoris short head more than the seated variation. Full bend and controlled 3-second eccentric. Useful when seated curl machine is occupied.',
  },
  {
    id: 'nordic-hamstring-curl',
    name: 'Nordic Hamstring Curl',
    nameDE: 'Nordische Beincurl',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 5,
    defaultWeight: 0,
    repRange: { min: 3, max: 8 },
    restSeconds: 120,
    scienceNote: 'Among the most effective hamstring strengtheners known — proven to reduce hamstring injury risk by up to 50% (Meta-analysis 2019). Eccentric: control the descent slowly. Extremely challenging for most people.',
  },

  // ── GLUTES ─────────────────────────────────────────────────────────────────

  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    nameDE: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['legs'],
    equipment: ['barbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 60,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Highest gluteus maximus EMG of any exercise. Shoulders on bench, chin to chest. Full hip extension and 1-second hold at top. Pad the bar for comfort. Progressive overload builds posterior power.',
  },
  {
    id: 'abductor-machine',
    name: 'Abductor',
    nameDE: 'Abduktoren Maschine',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 50,
    repRange: { min: 15, max: 25 },
    restSeconds: 60,
    scienceNote: 'Targets gluteus medius — essential for hip stability, gait, and injury prevention. Often underdeveloped in men. High reps with slow eccentric for best activation. Prevents knee valgus during squats.',
  },
  {
    id: 'adductor-machine',
    name: 'Adductor',
    nameDE: 'Adduktoren Maschine',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 50,
    repRange: { min: 15, max: 25 },
    restSeconds: 60,
    scienceNote: 'Strengthens inner thighs (adductors) — important for groin injury prevention and hip stability. Controls knee alignment. High reps work well as adductors have high slow-twitch fibre density.',
  },

  // ── ABS / CORE ─────────────────────────────────────────────────────────────

  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    nameDE: 'Kabelzug Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 25,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Cable allows progressive overload on abs — unlike bodyweight crunches. Flex from the hips DOWN, not from the neck. Maximally contract abs at the bottom. Most effective weighted ab exercise.',
  },
  {
    id: 'decline-crunch',
    name: 'Decline Crunch',
    nameDE: 'Decline Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 0,
    repRange: { min: 15, max: 25 },
    restSeconds: 60,
    scienceNote: 'Decline angle increases rectus abdominis ROM vs. flat crunches. Hands behind head (not pulling neck). Squeeze hard at the top — exhale fully. Add weight plate on chest to progress.',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    nameDE: 'Hängendes Beineheben',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
    repRange: { min: 10, max: 15 },
    restSeconds: 75,
    scienceNote: 'Posterior pelvic tilt at the top fully engages the rectus abdominis. Controlled descent prevents swinging. Advanced: straight legs. Beginner: knees bent. Strong anti-gravity core builder.',
  },
  {
    id: 'plank',
    name: 'Plank',
    nameDE: 'Unterarmstütz (Plank)',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 30, max: 60 },
    restSeconds: 60,
    scienceNote: 'Anti-extension isometric — maximizes deep core (transverse abdominis) without spinal flexion. Keep body in a perfectly straight line. Brace as if about to be punched. Progress to weighted vest or feet-elevated.',
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    nameDE: 'Ab-Rad Rollout',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders', 'back'],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 0,
    repRange: { min: 6, max: 12 },
    restSeconds: 90,
    scienceNote: 'Studies show highest rectus abdominis activation of any core exercise. Anti-extension demand requires full core bracing. Don\'t let hips sag. Start from knees until able to perform standing.',
  },

  // ── FOREARMS ───────────────────────────────────────────────────────────────

  {
    id: 'wrist-curl',
    name: 'Wrist Curl',
    nameDE: 'Handgelenkscurl',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: ['barbell', 'dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 15,
    repRange: { min: 15, max: 25 },
    restSeconds: 45,
    scienceNote: 'Wrist flexors (palmer side forearm) are trainable but rarely targeted. High reps work best as forearms have high slow-twitch density. Sit with forearms on thighs, full ROM at wrist.',
  },
  {
    id: 'reverse-wrist-curl',
    name: 'Reverse Wrist Curl',
    nameDE: 'Handgelenkscurl (Rückseite)',
    primaryMuscle: 'forearms',
    secondaryMuscles: [],
    equipment: ['barbell', 'dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 10,
    repRange: { min: 15, max: 25 },
    restSeconds: 45,
    scienceNote: 'Trains wrist extensors (dorsal forearm) — the antagonist to wrist flexors. Balancing both prevents elbow tendonitis (tennis elbow). Usually much weaker than the flexor side.',
  },
  {
    id: 'farmers-carry',
    name: 'Farmer\'s Carry',
    nameDE: 'Farmer\'s Walk',
    primaryMuscle: 'forearms',
    secondaryMuscles: ['core', 'shoulders', 'legs'],
    equipment: ['dumbbell', 'kettlebell'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 1,
    defaultWeight: 24,
    repRange: { min: 20, max: 40 },
    restSeconds: 90,
    scienceNote: 'Carries a huge overall stimulus — grip, traps, core anti-lateral-flexion, and conditioning simultaneously. Walk 20–40m per set. One of the most functional strength exercises for real-world carryover.',
  },

  // ── FUNCTIONAL / MOBILITY ──────────────────────────────────────────────────

  {
    id: 'dead-bug',
    name: 'Dead Bug',
    nameDE: 'Dead Bug',
    primaryMuscle: 'core',
    secondaryMuscles: ['back'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 0,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Excellent deep core stability exercise. Teaches the transverse abdominis to stabilize the spine during limb movement — this motor pattern transfers directly to athletic performance and injury prevention. Lower back must stay pressed to floor the entire time.',
  },
  {
    id: 'bird-dog',
    name: 'Bird Dog',
    nameDE: 'Bird Dog',
    primaryMuscle: 'core',
    secondaryMuscles: ['back', 'glutes'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Stuart McGill\'s research shows this is one of the safest and most effective exercises for spinal stability. Opposite arm/leg extension teaches rotational control. Spine must stay completely neutral — no rotation or dipping.',
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    nameDE: 'Gesäßbrücke',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['core', 'legs'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 0,
    repRange: { min: 15, max: 25 },
    restSeconds: 60,
    scienceNote: 'Foundation exercise for glute activation and posterior chain health. High reps with 1-second hold at top maximize gluteus maximus contraction. Essential prehab/activation before heavy leg work.',
  },
  {
    id: 'side-plank',
    name: 'Side Plank',
    nameDE: 'Seitstütz (Side Plank)',
    primaryMuscle: 'core',
    secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 20, max: 40 },
    restSeconds: 45,
    scienceNote: 'Anti-lateral-flexion isometric — trains quadratus lumborum and lateral core. Stuart McGill rates this as essential for spine health. Hips stacked, body in a straight line. Progress with feet stacked or adding hip dips.',
  },
  {
    id: 'superman-hold',
    name: 'Superman Hold',
    nameDE: 'Superman Hold',
    primaryMuscle: 'back',
    secondaryMuscles: ['glutes'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 0,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'Directly strengthens spinal erectors and multifidus — muscles that extend and protect the spine. Often weak in people with desk jobs. Hold each rep 1–2 seconds. Prevents lower back pain and improves posture significantly.',
  },
  {
    id: 'wall-angels',
    name: 'Wall Angels',
    nameDE: 'Wandengel',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 0,
    repRange: { min: 12, max: 20 },
    restSeconds: 45,
    scienceNote: 'Reactivates lower trapezius and serratus anterior — muscles that retract the shoulder blades. Reverses the effects of forward head posture and rounded shoulders from sitting. All points (head, back, arms) must maintain contact with the wall throughout.',
  },
  {
    id: 'pallof-press',
    name: 'Pallof Press',
    nameDE: 'Pallof Press',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['cable', 'band'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 15,
    repRange: { min: 12, max: 20 },
    restSeconds: 60,
    scienceNote: 'The gold standard anti-rotation core exercise. Resisting the cable\'s pull trains the obliques and transverse abdominis to prevent unwanted spinal rotation — directly transfers to heavy lifts and sport. Stand perpendicular to cable.',
  },
  {
    id: 'copenhagen-plank',
    name: 'Copenhagen Plank',
    nameDE: 'Kopenhagen Plank',
    primaryMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 3,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 15, max: 30 },
    restSeconds: 60,
    scienceNote: 'The most effective adductor strengthening exercise per 2021 evidence-based review. Reduces groin injury risk significantly in athletes. Top leg on bench — hold isometrically or add hip dips for added difficulty.',
  },
  {
    id: 'thoracic-rotation',
    name: 'Thoracic Rotation',
    nameDE: 'Brustwirbelsäulen Rotation',
    primaryMuscle: 'back',
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    category: 'functional',
    defaultSets: 2,
    defaultReps: 15,
    defaultWeight: 0,
    repRange: { min: 12, max: 20 },
    restSeconds: 45,
    scienceNote: 'Most people lack thoracic mobility — this is a common cause of shoulder and lower back injury. Kneeling T-spine rotation reopens the mid-back. Pause at end range each rep. Essential warm-up before pressing and pulling.',
  },
  {
    id: 'hip-90-90',
    name: 'Hip 90/90 Stretch',
    nameDE: 'Hüfte 90/90 Dehnung',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['legs'],
    equipment: ['bodyweight'],
    category: 'stretching',
    defaultSets: 2,
    defaultReps: 10,
    defaultWeight: 0,
    repRange: { min: 8, max: 12 },
    restSeconds: 30,
    scienceNote: 'Addresses hip internal and external rotation — restricted hips cause compensations up the entire chain (knee and lower back pain). Sit with both knees at 90° in opposite directions. Lean forward over front shin to deepen.',
  },

  // ── CARDIO ─────────────────────────────────────────────────────────────────

  {
    id: 'treadmill-run',
    name: 'Treadmill Run',
    nameDE: 'Laufband',
    primaryMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: ['cardio_machine'],
    category: 'cardio',
    isCardio: true,
    defaultSets: 1,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Zone 2 cardio (conversational pace, ~65% max HR) optimally builds aerobic base and cardiovascular health with minimal recovery cost. 20–45 min per session is sufficient for most training goals.',
  },
  {
    id: 'stationary-bike',
    name: 'Stationary Bike',
    nameDE: 'Ergometer / Fahrrad',
    primaryMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: ['cardio_machine'],
    category: 'cardio',
    isCardio: true,
    defaultSets: 1,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Low-impact cardio — excellent recovery tool and VO2max builder. HIIT (10x 30s sprint / 90s rest) or steady-state both improve cardiovascular fitness. Less joint stress than running.',
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    nameDE: 'Seilspringen',
    primaryMuscle: 'legs',
    secondaryMuscles: ['core', 'shoulders'],
    equipment: ['bodyweight'],
    category: 'cardio',
    isCardio: true,
    defaultSets: 3,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 60,
    scienceNote: 'Improves coordination, cardiovascular fitness, and calve strength simultaneously. 10 minutes of jump rope provides cardio equivalent to 30 min of jogging. Progressions: single leg, double-unders, cross-overs.',
  },
  {
    id: 'rowing-machine',
    name: 'Rowing Machine',
    nameDE: 'Rudergerät',
    primaryMuscle: 'back',
    secondaryMuscles: ['legs', 'core'],
    equipment: ['cardio_machine'],
    category: 'cardio',
    isCardio: true,
    defaultSets: 1,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Full-body cardio recruiting 86% of muscle mass — unmatched calorie burn. 70% legs / 30% upper body. Catch: legs straight. Drive: push legs, lean back, pull to lower chest. Damper usually at 3–5 for most people.',
  },

  // ── STRETCHING ─────────────────────────────────────────────────────────────

  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch (Lunge)',
    nameDE: 'Hüftbeuger Dehnung',
    primaryMuscle: 'legs',
    secondaryMuscles: ['core'],
    equipment: ['bodyweight'],
    category: 'stretching',
    defaultSets: 2,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Tight hip flexors (from sitting) tilt the pelvis forward causing lower back pain. Kneeling lunge stretch held 60–90 seconds per side restores neutral pelvis. Essential for anyone who sits >4h/day.',
  },
  {
    id: 'doorway-chest-stretch',
    name: 'Doorway Chest Stretch',
    nameDE: 'Brustdehnung im Türrahmen',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'],
    category: 'stretching',
    defaultSets: 2,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Counteracts chronically shortened pectorals from desk work and pressing. Stand in doorframe, forearms on both sides, gentle lean forward. Hold 60 seconds. Improves posture and shoulder mobility significantly.',
  },
  {
    id: 'lat-stretch',
    name: 'Lat Stretch',
    nameDE: 'Latissimus Dehnung',
    primaryMuscle: 'back',
    secondaryMuscles: ['shoulders'],
    equipment: ['bodyweight'],
    category: 'stretching',
    defaultSets: 2,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Tight lats restrict overhead shoulder mobility and can cause lower back pain due to anterior pelvic tilt. Grab a bar or rack, let bodyweight create the stretch. Hold 45–60 seconds per side.',
  },
  {
    id: 'hamstring-stretch',
    name: 'Lying Hamstring Stretch',
    nameDE: 'Ischiokrurale Dehnung',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'stretching',
    defaultSets: 2,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Tight hamstrings are a leading cause of posterior pelvic tilt and lower back pain. Lie on back, hold one leg up with strap or hands — keep the leg straight. Hold 60 seconds per side. Point/flex foot to vary emphasis.',
  },
  {
    id: 'childs-pose',
    name: 'Child\'s Pose',
    nameDE: 'Kindshaltung (Child\'s Pose)',
    primaryMuscle: 'back',
    secondaryMuscles: ['core', 'glutes'],
    equipment: ['bodyweight'],
    category: 'stretching',
    defaultSets: 2,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 1, max: 1 },
    restSeconds: 0,
    scienceNote: 'Decompresses the lumbar spine and stretches thoracic extensors, lats, and glutes simultaneously. Arms extended forward or alongside body. Breathe deeply into the back. Hold 60–90 seconds. Perfect post-workout recovery.',
  },
  {
    id: 'bayesian-biceps-curl',
    name: 'Bayesian Biceps Curl',
    nameDE: 'Bayesian Curls (Kabel)',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 10,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Facing away from the cable stack. Loads the biceps in the most lengthened position. Science shows significant increase in distal biceps hypertrophy due to the extreme stretch under load.',
  },
  {
    id: 'chest-supported-t-bar-row',
    name: 'Chest Supported T-Bar Row',
    nameDE: 'T-Bar Rudern (brustgestützt)',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['barbell', 'machine'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 40,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Eliminates structural fatigue. Allows for massive back volume without lower back being the limiting factor. S-tier for mid-back thickness.',
  },
  {
    id: 'single-arm-lat-pulldown',
    name: 'Single Arm Lat Pulldown',
    nameDE: 'Einarmiger Latzug (Kabel)',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 20,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Better scapular tracking than bilateral pulldowns. Allows you to pull in the plane of the lat for maximum recruitment. Great for correcting imbalances.',
  },
];

// ── Helper: Get exercise by ID ─────────────────────────────────────────────
export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find(e => e.id === id);
}

// ── Helper: Get exercises by muscle group ─────────────────────────────────
export function getExercisesByMuscle(muscle: string): Exercise[] {
  return exercises.filter(e => e.primaryMuscle === muscle || e.secondaryMuscles.includes(muscle as never));
}

// ── Helper: Get exercises by equipment ────────────────────────────────────
export function getExercisesByEquipment(equipment: string): Exercise[] {
  return exercises.filter(e => e.equipment.includes(equipment as never));
}

// ── Helper: Get cardio exercises ──────────────────────────────────────────
export function getCardioExercises(): Exercise[] {
  return exercises.filter(e => e.isCardio === true);
}

// ── Helper: Find exercise by name (fuzzy, for AI / voice matching) ─────────
export function findExerciseByName(name: string): Exercise | undefined {
  const q = name.toLowerCase().trim();
  // Exact match first (nameDE or name)
  const exact = exercises.find(
    e => e.nameDE.toLowerCase() === q || e.name.toLowerCase() === q
  );
  if (exact) return exact;
  // Partial match
  return exercises.find(
    e => e.nameDE.toLowerCase().includes(q) || e.name.toLowerCase().includes(q) ||
      q.includes(e.nameDE.toLowerCase()) || q.includes(e.name.toLowerCase())
  );
}
