import type { Exercise } from '@/types/exercises';

export const exercises: Exercise[] = [
  // ── BRUST ──────────────────────────────────────────────────────────────────
  {
    id: 'bench-press',
    name: 'Bench Press',
    nameDE: 'Bankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 60,
    repRange: { min: 6, max: 10 },
    restSeconds: 180,
    scienceNote: 'Ellbogen ca. 75° zum Körper halten — reduziert Schulterbelastung deutlich. Primäre Compound-Übung für Pectoralis Major mit dem höchsten Muskelaktivierungspotential.',
  },
  {
    id: 'incline-bench-press',
    name: 'Incline Bench Press',
    nameDE: 'Schrägbankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 50,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: '30–45° Neigung maximiert den oberen Pektoralis. Schulterblätter aktiv zusammenziehen, um Impingement zu vermeiden.',
  },
  {
    id: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    nameDE: 'Kurzhantel Bankdrücken',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 24,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Größerer Bewegungsradius als Langhantel — mehr Brustdehnung am unteren Punkt. Hände leicht nach innen drehen für bessere Kontraktion am oberen Punkt.',
  },
  {
    id: 'cable-fly',
    name: 'Cable Fly',
    nameDE: 'Kabelzug Flyes',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 15,
    repRange: { min: 12, max: 15 },
    restSeconds: 60,
    scienceNote: 'Kabel erzeugt konstante Spannung über den vollen Bewegungsradius. Arme leicht gebeugt halten — maximiert Pektoralis-Stretch ohne Gelenkbelastung.',
  },
  {
    id: 'dumbbell-fly',
    name: 'Dumbbell Fly',
    nameDE: 'Kurzhantel Flyes',
    primaryMuscle: 'chest',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
    repRange: { min: 12, max: 15 },
    restSeconds: 60,
    scienceNote: 'Kontrolliertes Absenken (3 Sek.) maximiert Muskelfaser-Rekrutierung. Arme leicht gebeugt, Fokus auf maximale Brustdehnung am unteren Punkt.',
  },
  {
    id: 'push-up',
    name: 'Push Up',
    nameDE: 'Liegestütz',
    primaryMuscle: 'chest',
    secondaryMuscles: ['shoulders', 'triceps'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 0,
    repRange: { min: 10, max: 20 },
    restSeconds: 60,
    scienceNote: 'Schulterblätter am Ende protraieren (nach vorne schieben) für vollständige Serratus-Aktivierung. Körper als gerade Linie halten — Hüfte nicht durchhängen lassen.',
  },
  {
    id: 'dips',
    name: 'Dips',
    nameDE: 'Dips',
    primaryMuscle: 'chest',
    secondaryMuscles: ['triceps', 'shoulders'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
    repRange: { min: 8, max: 15 },
    restSeconds: 90,
    scienceNote: 'Leichtes Vorbeugen (15–20°) verlagert Fokus auf Pektoralis. Ellbogen eng halten für mehr Trizeps-Aktivierung. Vollständige Streckung oben für maximalen Stimulus.',
  },

  // ── RÜCKEN ─────────────────────────────────────────────────────────────────
  {
    id: 'deadlift',
    name: 'Deadlift',
    nameDE: 'Kreuzheben',
    primaryMuscle: 'back',
    secondaryMuscles: ['glutes', 'legs', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 5,
    defaultWeight: 100,
    repRange: { min: 4, max: 6 },
    restSeconds: 180,
    scienceNote: 'Neutrale Wirbelsäule von Setup bis Lockout — runder Rücken erhöht Bandscheibendruck erheblich. Hüfte nach vorne drücken (nicht hochziehen). Stärkste Compound-Bewegung für die gesamte posteriore Kette.',
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    nameDE: 'Langhantelrudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 70,
    repRange: { min: 6, max: 10 },
    restSeconds: 120,
    scienceNote: 'Oberkörper 45° neigen, Stange zum Bauchnabel ziehen. Schulterblätter am Ende vollständig zusammendrücken. Höchste Latissimus-Aktivierung bei neutralem Untergriff.',
  },
  {
    id: 'pull-up',
    name: 'Pull Up',
    nameDE: 'Klimmzug',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 0,
    repRange: { min: 6, max: 12 },
    restSeconds: 120,
    scienceNote: 'Schulterblätter zuerst nach unten deprimieren (Scapular Pull) bevor die Ellbogen beugen. Vollständige Streckung unten für maximalen Latissimus-Stretch.',
  },
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    nameDE: 'Latzug',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 60,
    repRange: { min: 8, max: 12 },
    restSeconds: 90,
    scienceNote: 'Stange zum oberen Brustbein ziehen, nie hinter den Kopf — vermeidet HWS-Belastung. Leicht nach hinten lehnen und Brust herausstrecken für optimale Latzug-Mechanik.',
  },
  {
    id: 'seated-cable-row',
    name: 'Seated Cable Row',
    nameDE: 'Kabelzug Rudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['cable'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 50,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Schulterblätter am Ende vollständig retrahieren — macht 30% des Bewegungsweges aus. Rücken aufrecht halten, Momentum durch Schwung vermeiden.',
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    nameDE: 'Face Pull',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 20,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Zu den Ohren ziehen, Ellbogen hoch. Essenziell für Rotatorenmanschette und hinteres Schulterbalance. Reduziert Schulter-Verletzungsrisiko beim Drücken signifikant.',
  },
  {
    id: 'dumbbell-row',
    name: 'Dumbbell Row',
    nameDE: 'Kurzhantelrudern',
    primaryMuscle: 'back',
    secondaryMuscles: ['biceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 24,
    repRange: { min: 8, max: 12 },
    restSeconds: 90,
    scienceNote: 'Ellbogen eng am Körper führen, Stützhand aktiv nutzen. Schulterblatt vollständig retrahieren. Erlaubt höhere Lasten als Kabelzug durch direkten Kraftvektor.',
  },

  // ── SCHULTERN ──────────────────────────────────────────────────────────────
  {
    id: 'overhead-press',
    name: 'Overhead Press',
    nameDE: 'Schulterdrücken',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 50,
    repRange: { min: 6, max: 10 },
    restSeconds: 180,
    scienceNote: 'Kern anspannen, Rücken nicht überstrecken. Stange knapp vor dem Gesicht vorbeiführen — kurzer Weg, neutrale Wirbelsäule. Beste Übung für anterioren und medialen Deltakopf gleichzeitig.',
  },
  {
    id: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    nameDE: 'Kurzhantel Schulterdrücken',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['triceps'],
    equipment: ['dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 18,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Etwas breiterer Bewegungsradius als Langhantel. Handgelenke neutral halten. Kurzhanteln erlauben unilaterale Korrekturen bei Seiten-Dysbalancen.',
  },
  {
    id: 'lateral-raise',
    name: 'Lateral Raise',
    nameDE: 'Seitheben',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Kontrolliertes Absenken (3 Sek.) maximiert Time Under Tension. Daumen leicht nach unten (Gießkanne) für bessere mediale Deltakopf-Isolation. Kaum durch andere Übungen ersetzbar.',
  },
  {
    id: 'front-raise',
    name: 'Front Raise',
    nameDE: 'Vorwärtsheben',
    primaryMuscle: 'shoulders',
    secondaryMuscles: [],
    equipment: ['dumbbell', 'barbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 8,
    repRange: { min: 12, max: 15 },
    restSeconds: 60,
    scienceNote: 'Anteriorer Deltakopf wird bereits beim Bankdrücken und Schulterdrücken gut trainiert. Als Ergänzungsübung mit leichtem Gewicht und hohen Wdh. für komplette Schulterentwicklung.',
  },
  {
    id: 'rear-delt-fly',
    name: 'Rear Delt Fly',
    nameDE: 'Reverse Flyes',
    primaryMuscle: 'shoulders',
    secondaryMuscles: ['back'],
    equipment: ['dumbbell', 'cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 8,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Oberkörper 90° vorgebeugt, Arme mit leichter Beugung seitwärts heben. Hinterer Deltakopf ist oft unterentwickelt — direkte Arbeit verbessert Schulterbalance und Haltung deutlich.',
  },

  // ── BIZEPS ─────────────────────────────────────────────────────────────────
  {
    id: 'barbell-curl',
    name: 'Barbell Curl',
    nameDE: 'Langhantel Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['barbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 30,
    repRange: { min: 8, max: 12 },
    restSeconds: 90,
    scienceNote: 'Supinationsgriff maximiert Bizeps-Rekrutierung. Ellbogen stationär halten, Momentum durch Hüfte vermeiden. Zeigt die höchste EMG-Aktivierung aller Curl-Varianten.',
  },
  {
    id: 'dumbbell-curl',
    name: 'Dumbbell Curl',
    nameDE: 'Kurzhantel Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 14,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Supination am oberen Punkt (Handfläche nach außen drehen) für maximale Bizeps-Kontraktion. Erlaubt unilaterales Training — gleicht Seiten-Dysbalancen aus.',
  },
  {
    id: 'hammer-curl',
    name: 'Hammer Curl',
    nameDE: 'Hammer Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: ['forearms'],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 14,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Neutraler Griff aktiviert Brachialis und Brachioradialis stärker als Bizeps. Da Brachialis unter dem Bizeps liegt, vergrößert sein Training die sichtbare Armdicke effektiv.',
  },
  {
    id: 'incline-curl',
    name: 'Incline Dumbbell Curl',
    nameDE: 'Schrägbank Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: ['dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 12,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Schrägbank-Position verlängert den langen Bizepskopf — maximiert Dehnung am unteren Punkt. Studien zeigen signifikant höhere Bizeps-Aktivierung durch die verlängerte Ausgangsposition.',
  },
  {
    id: 'cable-curl',
    name: 'Cable Curl',
    nameDE: 'Kabel Curl',
    primaryMuscle: 'biceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 20,
    repRange: { min: 12, max: 15 },
    restSeconds: 60,
    scienceNote: 'Kabel erzeugt konstante Spannung auch am oberen Punkt — im Gegensatz zu Kurzhanteln. Als Finisher-Übung mit moderatem Gewicht für maximalen Pump ideal.',
  },

  // ── TRIZEPS ────────────────────────────────────────────────────────────────
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    nameDE: 'Trizeps Pushdown',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 30,
    repRange: { min: 12, max: 15 },
    restSeconds: 60,
    scienceNote: 'Ellbogen stationär an den Seiten halten. Vollständige Streckung am unteren Punkt für maximale Trizeps-Kontraktion. Seil-Variante erlaubt Außenrotation für bessere laterale Kopf-Aktivierung.',
  },
  {
    id: 'skull-crusher',
    name: 'Skull Crusher',
    nameDE: 'Skull Crusher',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['barbell', 'dumbbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 30,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Stange zur Stirn oder leicht dahinter führen — langen Trizepskopf maximal dehnen. Ellbogen eng zusammen, Schultern stabil. Exzellente Grundübung für Trizepsmasse.',
  },
  {
    id: 'overhead-tricep-extension',
    name: 'Overhead Tricep Extension',
    nameDE: 'Trizeps Extension',
    primaryMuscle: 'triceps',
    secondaryMuscles: [],
    equipment: ['dumbbell', 'cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 20,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Überkopf-Position bringt den langen Trizepskopf in vollständige Dehnung — höchste Aktivierung des Caput longum. Studien zeigen deutlich mehr Hypertrophie-Stimulus als Pushdowns.',
  },
  {
    id: 'close-grip-bench',
    name: 'Close Grip Bench Press',
    nameDE: 'Enges Bankdrücken',
    primaryMuscle: 'triceps',
    secondaryMuscles: ['chest', 'shoulders'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 50,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Griffbreite schulterbreit (nicht zu eng — belastet Handgelenke). Ellbogen eng am Körper — maximaler Trizeps-Fokus. Erlaubt höhere Lasten als reine Isolationsübungen.',
  },

  // ── BEINE ──────────────────────────────────────────────────────────────────
  {
    id: 'squat',
    name: 'Squat',
    nameDE: 'Kniebeuge',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes', 'core'],
    equipment: ['barbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 8,
    defaultWeight: 80,
    repRange: { min: 5, max: 8 },
    restSeconds: 180,
    scienceNote: 'Hüfte unter Kniehöhe senken für vollständige Quadrizeps-Aktivierung. Knie in Zehrichtung, Rücken neutral. Höchste anabole Hormonausschüttung aller Übungen — König der Beinübungen.',
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    nameDE: 'Beinpresse',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 120,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Füße hoch und breit für mehr Gluteus-Aktivierung, tief und eng für Quadrizeps-Fokus. Knie nie vollständig strecken (Gelenkschonung). Erlaubt höhere Lasten als Kniebeuge.',
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    nameDE: 'Beinstrecker',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 40,
    repRange: { min: 12, max: 15 },
    restSeconds: 60,
    scienceNote: 'Vollständige Streckung für maximale Quadrizeps-Kontraktion — 2 Sek. oben halten. Isoliert besonders den VMO (innerer Quadrizeps-Kopf) sehr effektiv.',
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    nameDE: 'Beinbeuger',
    primaryMuscle: 'legs',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 35,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Ischiokrurale Muskeln sind oft das schwache Glied. Vollständige Beugung, kontrolliertes Absenken (3 Sek.). Liegend aktiviert den kurzen Bizeps-Femoris-Kopf stärker.',
  },
  {
    id: 'romanian-deadlift',
    name: 'Romanian Deadlift',
    nameDE: 'Rumänisches Kreuzheben',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes', 'back'],
    equipment: ['barbell', 'dumbbell'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 70,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Hüfte nach hinten schieben (nicht nach unten), Knie leicht gebeugt. Maximale Dehnung der Ischiokruralen am unteren Punkt. Exzellente Übung für die hintere Oberschenkelkette.',
  },
  {
    id: 'lunges',
    name: 'Lunges',
    nameDE: 'Ausfallschritte',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['barbell', 'dumbbell', 'bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 0,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Großer Schritt nach vorne, Knie 90°, Oberkörper aufrecht. Unilaterales Training deckt Seiten-Dysbalancen auf und verbessert funktionale Beweglichkeit.',
  },
  {
    id: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    nameDE: 'Bulgarische Kniebeuge',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['barbell', 'dumbbell', 'bodyweight'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 0,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Hinteres Bein auf Bank, vorderes Bein 60–70 cm davor. Tiefer gehen als normale Kniebeuge möglich. Studien zeigen ähnliche Quadrizeps-Aktivierung wie Kniebeuge bei deutlich geringerer Wirbelsäulenbelastung.',
  },
  {
    id: 'hack-squat',
    name: 'Hack Squat',
    nameDE: 'Hack Squat',
    primaryMuscle: 'legs',
    secondaryMuscles: ['glutes'],
    equipment: ['machine'],
    category: 'compound',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 80,
    repRange: { min: 8, max: 12 },
    restSeconds: 120,
    scienceNote: 'Aufrechter Oberkörper entlastet die Wirbelsäule stark. Füße tief positioniert für maximalen Quadrizeps-Fokus. Maschine erlaubt tiefes Gehen ohne Balance-Anforderung.',
  },

  // ── GESÄSS ──────────────────────────────────────────────────────────────────
  {
    id: 'hip-thrust',
    name: 'Hip Thrust',
    nameDE: 'Hip Thrust',
    primaryMuscle: 'glutes',
    secondaryMuscles: ['legs'],
    equipment: ['barbell'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 12,
    defaultWeight: 60,
    repRange: { min: 10, max: 15 },
    restSeconds: 90,
    scienceNote: 'Schulterblätter auf Bank, Kinn zur Brust. Hüfte voll strecken und 1 Sek. oben halten. Höchste Gluteus-Maximus-Aktivierung aller Übungen laut EMG-Studien.',
  },
  {
    id: 'cable-kickback',
    name: 'Cable Kickback',
    nameDE: 'Kabel Kickback',
    primaryMuscle: 'glutes',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 15,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Hüfte nicht rotieren — Bewegung nur aus dem Hüftgelenk. Langsam absenken (3 Sek.). Isoliert den Gluteus Maximus effektiv ohne Rückenbelastung.',
  },

  // ── CORE ───────────────────────────────────────────────────────────────────
  {
    id: 'plank',
    name: 'Plank',
    nameDE: 'Plank',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 1,
    defaultWeight: 0,
    repRange: { min: 30, max: 60 },
    restSeconds: 60,
    scienceNote: 'Körper als gerade Linie halten — 30–60 Sekunden pro Satz. Hohe isometrische Anti-Extensionskraft des Core. Schulterblätter aktiv nach unten drücken.',
  },
  {
    id: 'cable-crunch',
    name: 'Cable Crunch',
    nameDE: 'Kabel Crunch',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['cable'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 20,
    repRange: { min: 15, max: 20 },
    restSeconds: 60,
    scienceNote: 'Vom Hüftgelenk beugen, nicht vom Nacken. Bauch am unteren Punkt maximal zusammenziehen. Kabel ermöglicht progressive Lasterhöhung — effektiver als ungewichtete Crunches.',
  },
  {
    id: 'hanging-leg-raise',
    name: 'Hanging Leg Raise',
    nameDE: 'Hängendes Beineheben',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 15,
    defaultWeight: 0,
    repRange: { min: 10, max: 15 },
    restSeconds: 60,
    scienceNote: 'Beckenkippung am oberen Punkt für maximale Rectus-Aktivierung. Kontrolliertes Absenken verhindert Schwingen. Fortgeschrittene Variante: gestreckte Beine für höheren Hebel.',
  },
  {
    id: 'ab-wheel',
    name: 'Ab Wheel Rollout',
    nameDE: 'Ab-Rad Rollout',
    primaryMuscle: 'core',
    secondaryMuscles: [],
    equipment: ['bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 10,
    defaultWeight: 0,
    repRange: { min: 8, max: 15 },
    restSeconds: 60,
    scienceNote: 'Rücken nicht durchhängen lassen — hohe Anti-Extensionskraft des Core aufbauen. Studien zeigen höchste Rectus-Abdominis-Aktivierung aller Core-Übungen.',
  },

  // ── WADEN ──────────────────────────────────────────────────────────────────
  {
    id: 'calf-raise',
    name: 'Calf Raise',
    nameDE: 'Wadenheben',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['machine', 'barbell', 'dumbbell', 'bodyweight'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 40,
    repRange: { min: 15, max: 25 },
    restSeconds: 60,
    scienceNote: 'Wadenmuskulatur besteht zu 75% aus langsamen Muskelfasern — hohe Wiederholungszahlen sind effektiver. Vollständige Streckung und maximale Beugung für kompletten Stimulus.',
  },
  {
    id: 'seated-calf-raise',
    name: 'Seated Calf Raise',
    nameDE: 'Sitzend Wadenheben',
    primaryMuscle: 'calves',
    secondaryMuscles: [],
    equipment: ['machine'],
    category: 'isolation',
    defaultSets: 3,
    defaultReps: 20,
    defaultWeight: 30,
    repRange: { min: 15, max: 25 },
    restSeconds: 60,
    scienceNote: 'Sitzend isoliert den Soleus (tiefer Wadenmuskel) — bei gebeugtem Knie ist Gastrocnemius entspannt. Ergänzt stehendes Wadenheben perfekt für vollständige Wadenentwicklung.',
  },
];

// Helper: Übung nach ID finden
export function getExerciseById(id: string): Exercise | undefined {
  return exercises.find((e) => e.id === id);
}

// Helper: Übungen nach Muskelgruppe filtern
export function getExercisesByMuscle(muscle: string): Exercise[] {
  return exercises.filter(
    (e) => e.primaryMuscle === muscle || e.secondaryMuscles.includes(muscle as never)
  );
}

// Helper: Übungen nach Equipment filtern
export function getExercisesByEquipment(equipment: string): Exercise[] {
  return exercises.filter((e) => e.equipment.includes(equipment as never));
}
